FROM simeononsecurity/acng:latest

# Set DEBIAN_FRONTEND to noninteractive to prevent interactive prompts during package installations
ENV DEBIAN_FRONTEND=noninteractive

ENV ACNG_LOCALE="us"

RUN set -uex; \
    if [ -n "$ACNG_LOCALE" ]; then \
      cp /etc/apt-cacher-ng/acng.conf.$ACNG_LOCALE /etc/apt-cacher-ng/acng.conf; \
    fi; \
